### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by rttsve** [xvrh/atlassian_apis#10]
Performing hot restart...
Syncing files to device AOSP on IA Emulator...
Restarted application in 292ms.
E/flutter (10192): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (10192): #0      main (package:untitled/main.dart:8:52)
E/flutter (10192): #1      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:130:25)
E/flutter (10192): #2      _rootRun (dart:async/zone.dart:1426:13)
E/flutter (10192): #3      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (10192): #4      _runZoned (dart:async/zone.dart:1861:10)
E/flutter (10192): #5      runZonedGuarded (dart:async/zone.dart:1849:12)
E/flutter (10192): #6      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
E/flutter (10192): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (10192): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (10192): 
`
import 'dart:io';
import 'package:atlassian_apis/jira_platform.dart';

void main() async {
  // This example uses API Token authentication.
  // Alternatively, you can use OAuth.
  var user = Platform.environment['User-email']!;
  var apiToken = Platform.environment['api token']!;

  // Create an authenticated http client.
  var client = ApiClient.basicAuthentication(
      Uri.https('cloud url', ''),
      user: user,
      apiToken: apiToken);

  // Create the API wrapper from the http client
  var jira = JiraPlatformApi(client);

  // Communicate with the APIs..
  await jira.projects.searchProjects();

  // Close the client to quickly terminate the process
  client.close();
}

`

**Comment by xvrh** [comment]
`Platform.environment` uses the environment variables from your machine. Check that this variable exist (ie. `echo $UserEmail`)

Also I'm not sure you can have dash (-) and spaces in them (`Platform.environment['api token']!`) is probably invalid.

**Comment by rttsve** [comment]
(echo $UserEmail) indeed missing from platform.dart - how i can switch to proper variables ?

**Comment by xvrh** [comment]
I think in your case you should just put the constants in your code:

```dart
void main() {
  var user = 'xxx@gmail.com'; // Your email
  var apiToken = 'abc1332qsdfazez'; // Your token

  var client = ApiClient.basicAuthentication(
      Uri.https('cloud url', ''),
      user: user,
      apiToken: apiToken);

  //...
}
```
