### ISSUE TITLE
400 : "Invalid request payload" on updateFilter

### ISSUE THREAD

**Issue by alevinetx** [xvrh/atlassian_apis#26]
atlassian_apis: ^0.10.0

This started just a few days ago, and it was working prior, no changes since. I just upgraded to 0.10.0 thinking that would be the fix needed, but the problem persists.

```
      print("updating filter with new jql");
      print(jql);
      var myfilter = await filters.getFilter(id: 39814);
      var newFilter = myfilter.copyWith(jql: jql);
      print("Json is  ${json.encode(newFilter)}");

      await filters.updateFilter(id: 39814, body: newFilter);
```

gives me

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: JiraException(400, Bad Request, url: https://abcdef.atlassian.net/rest/api/3/filter/39814?, message: {"errorMessages":["Invalid request payload. Refer to the REST API documentation and try again."]})
#0      ApiException.checkResponse (package:atlassian_apis/src/api_utils.dart:138:5)
#1      ApiClient.send (package:atlassian_apis/src/api_utils.dart:84:18)
<asynchronous suspension>
#2      FiltersApi.updateFilter (package:atlassian_apis/src/generated/jira_platform.dart:1873:28)
<asynchronous suspension>
```

I'm at a loss.  Is there something I can help provide with tracking the issue?

Thank you !

**Comment by xvrh** [comment]
@alevinetx I quickly tried something similar like this:

```dart
import 'dart:io';
import 'package:atlassian_apis/jira_platform.dart';

void main() async {
  var user = Platform.environment['ATLASSIAN_USER']!;
  var apiToken = Platform.environment['ATLASSIAN_API_TOKEN']!;

  var client = ApiClient.basicAuthentication(
      Uri.https('xxx.atlassian.net', ''),
      user: user,
      apiToken: apiToken);
  var jira = JiraPlatformApi(client);

  var myFilter = await jira.filters.getFilter(id: 12497);
  myFilter = myFilter.copyWith(jql: 'assignee in (currentUser()) order by created ASC');

  await jira.filters.updateFilter(id: 12497, body: myFilter);

  client.close();
}
```

But I don't have any problem.

Can you share your new `jql`? Maybe try to simplify the request to understand exactly what is causing the error.
ie. you can only send a few fields in the update request:
```dart
await jira.filters.updateFilter(id: 12497, body: Filter(name: 'New name', description: 'New description'));
```

**Comment by alevinetx** [comment]
I set my jql as simple as possible "project = myproj", and still with the failure
Here's the sanitized dump from the encoding line 

code:
```
print("updating filter with new jql");
      jql = "project = myproj";
      print(jql);
      var myfilter = await filters.getFilter(id: 39814);
      var newFilter = myfilter.copyWith(jql: jql);
      print("Json is  ${json.encode(newFilter)}");

      await filters.updateFilter(id: 39814, body: newFilter);
```

sanitized filter:
```
{
	"self": "https://abcde.atlassian.net/rest/api/3/filter/39814",
	"id": "39814",
	"name": "myproject-2023",
	"description": "",
	"owner": {
		"self": "https://abcde.atlassian.net/rest/api/3/user?accountId=1111:123-123-1332-abcd",
		"accountId": "1111:123-123-1334-abcd",
		"avatarUrls": {
			"16x16": "https://secure.gravatar.com/avatar/abcd?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAL-6.png",
			"24x24": "https://secure.gravatar.com/avatar/abcd?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAL-6.png",
			"32x32": "https://secure.gravatar.com/avatar/abcd?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAL-6.png",
			"48x48": "https://secure.gravatar.com/avatar/abcd?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAL-6.png"
		},
		"displayName": "My Name",
		"active": true
	},
	"jql": "project = myproj",
	"viewUrl": "https://abcde.atlassian.net/issues/?filter=39814",
	"searchUrl": "https://abcde.atlassian.net/rest/api/3/search?jql=project+%3D+myproj+and+linkedissue+in+(+myproj-13610,myproj-13609,myproj-13562,myproj-13554,myproj-13553,myproj-13537,myproj-13526,myproj-13513,myproj-13512,myproj-13511+)+or+key+in+(myproj-13617,myproj-13615,myproj-13552,myproj-13525,myproj-13523,myproj-13510)",
	"favourite": true,
	"favouritedCount": 1,
	"sharePermissions": [
		{
			"id": 105371,
			"type": "project",
			"project": {
				"self": "https://abcde.atlassian.net/rest/api/3/project/1234",
				"id": "1234",
				"key": "myproj",
				"components": [],
				"issueTypes": [],
				"assigneeType": "PROJECT_LEAD",
				"versions": [],
				"name": "MyProject",
				"roles": {},
				"avatarUrls": {
					"16x16": "https://abcde.atlassian.net/rest/api/3/universal_avatar/view/type/project/avatar/10400?size=xsmall",
					"24x24": "https://abcde.atlassian.net/rest/api/3/universal_avatar/view/type/project/avatar/10400?size=small",
					"32x32": "https://abcde.atlassian.net/rest/api/3/universal_avatar/view/type/project/avatar/10400?size=medium",
					"48x48": "https://abcde.atlassian.net/rest/api/3/universal_avatar/view/type/project/avatar/10400"
				},
				"projectCategory": {
					"self": "https://abcde.atlassian.net/rest/api/3/projectCategory/10004",
					"id": "10004",
					"name": "MyProject",
					"description": ""
				},
				"projectTypeKey": "software",
				"simplified": false,
				"style": "classic",
				"favourite": false,
				"isPrivate": false,
				"properties": {},
				"deleted": false,
				"archived": false
			}
		}
	],
	"editPermissions": [],
	"sharedUsers": {
		"size": 3206,
		"items": [],
		"max-results": 1000,
		"start-index": 0,
		"end-index": 0
	},
	"subscriptions": {
		"size": 0,
		"items": [],
		"max-results": 1000,
		"start-index": 0,
		"end-index": 0
	}
}
```

**Comment by alevinetx** [comment]
Well, thank you, found the problem!!

I used your simple line,  ```await jira.filters.updateFilter(id: 12497, body: Filter(name: 'New name', description: 'New description'));```

And it worked, and then my update worked as prior.

It seems they may have changed the requirements for field presence, and as I'd never set those, it was complaining, but with not a very good error message.

Thank you for taking the time to help me out, I truly appreciate it.  I need to send their team feedback to make it known when they start changing required fields, etc.

**Comment by xvrh** [comment]
@alevinetx all the tools are written in Dart and are committed in this project.
ie.:
- Pull all the openapis/swagger schema: run this script https://github.com/xvrh/atlassian_apis/blob/master/tool/update_swagger_files.dart
- Generate all the Dart clients: https://github.com/xvrh/atlassian_apis/blob/master/tool/generate_client.dart

This is basically a home-made swagger generator customized for the specificities of the atlassian schemas.

**Comment by alevinetx** [comment]
bingo bango, found the problem!

Per the API spec, the problem is in the `Project` field, which only uses a `subset of the properties, which are: self, id, key, assigneeType, name, roles, avatarUrls, projectType, simplified.`

Once I stripped out these fields, I can `PUT` the request using a REST tool (eg, Insomnia)

```
	"components": [],
	"issueTypes": [],
	"versions": [],			
	"projectCategory": {},
	"projectTypeKey": "software",		
	"style": "classic",
	"favourite": false,
	"isPrivate": false,
	"properties": {},
	"deleted": false,
	"archived": false
```

**Comment by alevinetx** [comment]
Some starter code for anyone.  Not sure how you want to handle this, as most the code is autogenerated from API specs

```dart
  // build up the permissions, minus bad fields

  List<String> badKeys = [
    "components",
    "issueTypes",
    "versions",
    "projectCategory",
    "projectTypeKey",
    "style",
    "favourite",
    "isPrivate",
    "properties",
    "deleted",
    "archived"
  ];

  List<Map<String, Object?>> replacementPermissions = [];

  List<SharePermission> permissions = List<SharePermission>.from(myfilter.sharePermissions);
  for (SharePermission sp in permissions)
  {
    var permMap = sp.toJson();

    var projMap = permMap["project"] as Map<String, Object?>;
    for (String key in badKeys)
    {
      projMap.remove(key);
    }

    permMap.remove("project");
    MapEntry<String, Object?> replacement = MapEntry("project",projMap);
    permMap.addEntries([replacement]);

    replacementPermissions.add(permMap);

  } // sp in permissions

  // slice and dice the filter
  var filterMap = newFilter.toJson();
  filterMap.remove("sharePermissions");
  MapEntry<String, Object?> replacement = MapEntry("sharePermissions",replacementPermissions);
  filterMap.addEntries([replacement]);

  var updatedFilterResponse = await client.send(
    'put',
    'rest/api/3/filter/{id}',
    pathParameters: {
      'id': '$my_filter',
    },
    queryParameters: {},
    body: filterMap,
  );
```

**Comment by xvrh** [comment]
@alevinetx thanks for looking into this.

Just a quick question though: if all you want is to update the `jql` field, can't you send a request with only that field?
ie:
```dart
await jira.filters.updateFilter(id: 123, body: Filter(jql: '<new jql>'));
```

Will it change any other field?

**Comment by alevinetx** [comment]
Yes, as that new Filter() no longer carries any share permissions, which was what was causing me problems; it was getting updated but then it broke people being able to use it.

`update` should be considered a `replace` in true functionality.

**Comment by xvrh** [comment]
@alevinetx In the `updateFilter` method, there is a `overrideSharePermissions` parameter. Does it changes anything if you put it to `false`?

```dart
await jira.filters.updateFilter(id: 123, body: Filter(jql: '<new jql>'), overrideSharePermissions: false);
```

**Comment by alevinetx** [comment]
Sadly, no

> overrideSharePermissions
boolean

EXPERIMENTAL: Whether share permissions are overridden to enable the addition of any share permissions to filters. Available to users with Administer Jira [global permission](https://confluence.atlassian.com/x/x4dKLg)

**Comment by alevinetx** [comment]
BTW, there's an additional parameter, `editPermissions`, which follows the same subset of `Project`.  As I don't personally use it, I didn't include it in my starter code above, but that's an easy enough copy-paste.

**Comment by alevinetx** [comment]
I see your `fixApi()` call. Is that where you'd likely do some conditional to create a copy of `SharePermission` with the subset of fields, a one-off `Filter`,  and also modify the `updateFilter` call to use the one-off?

**Comment by xvrh** [comment]
I think it's gonna be hard to handle that in the generator...

As a first step, I suggest you handle it in your own code with something like that:

```dart
void main() async {
  await jira.filters
    .updateFilter(id: 12497, body: prepareFilterForUpdate(myFilter));
}

Filter prepareFilterForUpdate(Filter filter) {
  return filter.copyWith(editPermissions: [
    for (var permission in filter.editPermissions)
      _prepareSharePermission(permission)
  ]);
}

SharePermission _prepareSharePermission(SharePermission permission) {
  var project = permission.project;
  if (project != null) {
    return permission.copyWith(project: Project(id: project.id));
  }
  return permission;
}
```

Would it work?

After, we can maintain utilities like `prepareFilterForUpdate` in this package and tell the generator to add it in the generated code for the `updateFilter` method...

**Comment by alevinetx** [comment]
I'm pretty sure `Filter` will need to have its own special class, as the json method will still see the fields in `project`, and send empty values.  That's why I was suggesting wiring it into the `fixApi()`, as that's where it seems you're doing any special magic.  

Or, we just add a shadow `updateFilterWithPermissions` that uses the field removal from the `Map` in `Filter` before sending it along.   

The 2nd would probably be the cleanest.

**Comment by alevinetx** [comment]
> BTW, there's an additional parameter, `editPermissions`, which follows the same subset of `Project`. As I don't personally use it, I didn't include it in my starter code above, but that's an easy enough copy-paste.

As soon as I said this, I now need it.  

Fun fact:  the `editPermissions` block in the returned `Filter` doesn't contain a `Project` node.  So it has to be added in.   /sigh

updated code to come

**Comment by alevinetx** [comment]
still has some artifacts from moving things around (late before used only in the loop), but functional

```

      List<SharePermission> permissions = List<SharePermission>.from(myfilter.sharePermissions);
      List<SharePermission> editPermissions = List<SharePermission>.from(myfilter.editPermissions);

      var newFilter = myfilter.copyWith(jql: jql);



    // build up the permissions, minus bad fields
    List<String> badKeys = [
      "components",
      "issueTypes",
      "versions",
      "projectCategory",
      "projectTypeKey",
      "style",
      "favourite",
      "isPrivate",
      "properties",
      "deleted",
      "archived"
    ];

    List<Map<String, Object?>> replacementPermissions = [];

    late MapEntry<String, Object?> projectReplacement;
    // share permissions
    for (SharePermission sp in permissions)
    {
      var permMap = sp.toJson();
      var projMap = permMap["project"] as Map<String, Object?>;
      for (String key in badKeys)
        {
          projMap.remove(key);
        }
      permMap.remove("project");
      projectReplacement = MapEntry("project",projMap);
      permMap.addEntries([projectReplacement]);
      replacementPermissions.add(permMap);
    }

    // edit permissions
    List<Map<String, Object?>> editReplacementPermissions = [];
    for (SharePermission sp in editPermissions)
    {
      var permMap = sp.toJson();

      // remove user.avatarUrls
      (permMap['user'] as Map<String, Object?>).remove('avatarUrls');

      editReplacementPermissions.add(permMap);
    }

    // slice and dice the filter
    var filterMap = newFilter.toJson();
    filterMap.remove("sharePermissions");
    MapEntry<String, Object?> replacement = MapEntry("sharePermissions",replacementPermissions);
    filterMap.addEntries([replacement]);

    filterMap.remove("editPermissions");
    MapEntry<String, Object?> editReplacement = MapEntry("editPermissions",editReplacementPermissions);
    filterMap.addEntries([editReplacement]);

    print("New filter: ${json.encode(filterMap)}");

    var updatedFilterResponse = await client.send(
      'put',
      'rest/api/3/filter/{id}',
      pathParameters: {
        'id': '$my_filter',
      },
      queryParameters: {},
      body: filterMap,
    );

```

**Comment by alevinetx** [comment]
some updates w/ Atlassian
![image](https://user-images.githubusercontent.com/5067356/221224918-8a301cea-a263-4e39-9415-d10258a116a1.png)
![image](https://user-images.githubusercontent.com/5067356/221225025-2d906d84-8b7b-40ae-a820-88d0f4cd42a5.png)
![image](https://user-images.githubusercontent.com/5067356/221225113-e160da79-c47c-4b8d-812c-46d13589e03d.png)
